In [41]:
import numpy as np
import pandas as pd
from statsmodels.formula.api import ols
import statsmodels.api as sm
from patsy import dmatrices,dmatrix, demo_data
import seaborn as sns

In [3]:
df = pd.read_csv("cities_data.csv")

In [4]:
df.head()

,Children,Car,HHIncome,ID,Elderly,City,CityShape,RoadDens,TransSup,LN_INC,Worker,VKMS,LN_VKMS
0,0,1,488,1,0,1,0.72021,0.859273,1.13149,6.192362,1,11591.44594,9.358023
1,0,1,753,2,0,1,0.72021,0.859273,1.13149,6.625392,1,7841.81934,8.967226
2,0,1,623,3,0,1,0.72021,0.859273,1.13149,6.436150,1,10325.07654,9.242331
3,2,2,634,4,0,1,0.72021,0.859273,1.13149,6.453625,1,23139.36207,10.049290
4,0,2,1039,5,0,1,0.72021,0.859273,1.13149,6.946976,1,12938.27998,9.467946

### A. Descriptive Statistics

In [13]:
df.describe() ##Summary statistics

,Children,Car,HHIncome,ID,Elderly,City,CityShape,RoadDens,TransSup,LN_INC,Worker,VKMS,LN_VKMS
count,4562.000000,4562.000000,4562.000000,4562.000000,4562.000000,4562.000000,4562.000000,4562.000000,4562.000000,4562.000000,4562.000000,4562.000000,4562.000000
mean,0.773345,1.246602,620.681938,2483.753617,0.140728,25.333626,0.739916,0.713547,0.897926,6.287665,0.731039,17701.429313,9.503314
std,1.028602,0.431080,349.572470,1444.400617,0.347779,14.439618,0.137404,0.280034,0.462799,0.610125,0.443468,12327.546913,0.792082
min,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.513632,0.247698,0.000000,0.000000,0.000000,553.665294,6.316560
25%,0.000000,1.000000,406.000000,1243.500000,0.000000,13.000000,0.608285,0.503388,0.596759,6.008813,0.000000,7554.533455,8.929903
50%,0.000000,1.000000,606.000000,2477.500000,0.000000,25.000000,0.723885,0.735855,0.870499,6.408529,1.000000,13730.304505,9.527361
75%,2.000000,1.000000,761.000000,3726.750000,0.000000,38.000000,0.859690,0.927846,1.102259,6.635947,1.000000,26332.095235,10.178544
max,5.000000,2.000000,10558.000000,5000.000000,1.000000,50.000000,0.998501,1.239332,1.993351,9.264734,1.000000,49186.110800,10.803367

In [14]:
df.corr() ##Correlation table

,Children,Car,HHIncome,ID,Elderly,City,CityShape,RoadDens,TransSup,LN_INC,Worker,VKMS,LN_VKMS
Children,1.000000,0.119654,0.240474,-0.000579,-0.303684,-0.000310,0.025613,0.009752,-0.035165,0.276344,0.339289,0.307028,0.310623
Car,0.119654,1.000000,0.215971,-0.035216,-0.133548,-0.035411,-0.019800,-0.002139,-0.016825,0.202813,0.172699,0.274322,0.269293
HHIncome,0.240474,0.215971,1.000000,-0.003067,-0.305791,-0.002598,0.007761,-0.003320,-0.015871,0.794713,0.412667,0.326434,0.352935
ID,-0.000579,-0.035216,-0.003067,1.000000,0.015682,0.999801,0.096938,-0.017664,-0.124800,0.000267,-0.028814,0.009894,0.043300
Elderly,-0.303684,-0.133548,-0.305791,0.015682,1.000000,0.015142,0.004539,-0.022993,0.007727,-0.351640,-0.667191,-0.234496,-0.236160
City,-0.000310,-0.035411,-0.002598,0.999801,0.015142,1.000000,0.097043,-0.017697,-0.124843,0.000700,-0.028475,0.010072,0.043360
CityShape,0.025613,-0.019800,0.007761,0.096938,0.004539,0.097043,1.000000,-0.035498,-0.220422,-0.000240,0.002061,-0.003807,-0.002466
RoadDens,0.009752,-0.002139,-0.003320,-0.017664,-0.022993,-0.017697,-0.035498,1.000000,-0.110733,-0.005355,0.016134,0.573153,0.576853
TransSup,-0.035165,-0.016825,-0.015871,-0.124800,0.007727,-0.124843,-0.220422,-0.110733,1.000000,-0.026830,-0.016930,-0.278342,-0.300387
LN_INC,0.276344,0.202813,0.794713,0.000267,-0.351640,0.000700,-0.000240,-0.005355,-0.026830,1.000000,0.530311,0.377371,0.446553
Worker,0.339289,0.172699,0.412667,-0.028814,-0.667191,-0.028475,0.002061,0.016134,-0.016930,0.530311,1.000000,0.305495,0.311581
VKMS,0.307028,0.274322,0.326434,0.009894,-0.234496,0.010072,-0.003807,0.573153,-0.278342,0.377371,0.305495,1.000000,0.935473
LN_VKMS,0.310623,0.269293,0.352935,0.043300,-0.236160,0.043360,-0.002466,0.576853,-0.300387,0.446553,0.311581,0.935473,1.000000

In [36]:
for a in df.columns: ## Frequency table
    print("---- %s ---" % a)
    print(df[a].value_counts())

---- Children ---
0    2632
2     894
1     703
3     301
4      26
5       6
Name: Children, dtype: int64
---- Car ---
1    3437
2    1125
Name: Car, dtype: int64
---- HHIncome ---
508     45
609     41
607     39
608     36
623     35
        ..
1042     1
1584     1
1624     1
1824     1
1971     1
Name: HHIncome, Length: 965, dtype: int64
---- ID ---
2049    1
1242    1
1254    1
3299    1
1250    1
       ..
577     1
4675    1
2628    1
581     1
2047    1
Name: ID, Length: 4562, dtype: int64
---- Elderly ---
0    3920
1     642
Name: Elderly, dtype: int64
---- City ---
19    97
2     96
1     96
25    96
27    95
18    95
14    95
8     95
17    95
4     95
28    94
20    93
48    93
34    93
6     93
38    93
16    93
37    93
26    92
46    92
22    92
36    92
31    92
9     92
5     92
40    92
3     92
50    91
21    91
7     90
44    90
41    90
32    90
11    89
15    89
12    89
45    89
29    89
35    88
23    88
47    88
30    88
49    88
42    87
13    87
39    87
43    87
24    87
33    86
10    86
Name: City, dtype: int64
---- CityShape ---
0.659091    97
0.720210    96
0.622093    96
0.796486    96
0.791438    95
0.589207    95
0.630254    95
0.570584    95
0.975623    95
0.513632    95
0.723885    94
0.867271    93
0.749957    93
0.803867    93
0.600736    93
0.646035    93
0.805393    93
0.561121    93
0.865912    92
0.844672    92
0.720426    92
0.681304    92
0.790311    92
0.833853    92
0.895113    92
0.990355    92
0.956103    92
0.745319    91
0.715104    91
0.531127    90
0.575707    90
0.817420    90
0.649572    90
0.998501    89
0.859690    89
0.608285    89
0.596502    89
0.576203    89
0.863885    88
0.818623    88
0.740827    88
0.915626    88
0.893478    88
0.910768    87
0.547799    87
0.576741    87
0.947100    87
0.661716    87
0.722351    86
0.535485    86
Name: CityShape, dtype: int64
---- RoadDens ---
0.739812    97
0.859273    96
0.775964    96
0.544680    96
0.927846    95
1.112675    95
0.679457    95
0.953753    95
0.368119    95
0.477486    95
0.874632    94
1.195216    93
1.106001    93
0.310819    93
0.738346    93
0.557652    93
0.247698    93
0.515499    93
0.866061    92
0.342870    92
0.735855    92
1.133758    92
0.912331    92
0.373302    92
0.605366    92
0.654020    92
0.354721    92
0.984741    91
0.575537    91
0.312126    90
1.068859    90
1.136747    90
0.660886    90
0.651315    89
1.239332    89
0.503388    89
0.291986    89
0.515351    89
1.146617    88
0.558024    88
0.799469    88
0.374197    88
0.578192    88
1.085009    87
0.773160    87
0.813190    87
0.857960    87
0.351519    87
0.409782    86
1.025095    86
Name: RoadDens, dtype: int64
---- TransSup ---
0.000000    179
1.640477     97
1.492690     96
1.700071     96
1.131490     96
1.993351     95
0.917932     95
1.102259     95
0.593500     95
0.596759     95
1.432686     95
0.727576     94
0.897046     93
0.407332     93
1.004266     93
0.527550     93
0.972835     93
1.712502     93
1.595192     93
1.343901     92
0.662347     92
0.563291     92
0.939738     92
0.790293     92
1.024800     92
1.262074     92
0.960912     92
0.895931     91
0.957065     91
0.258219     90
0.878765     90
0.803815     90
0.733766     90
0.792366     89
0.345800     89
1.786341     89
0.440136     89
0.821469     89
0.756638     88
0.621738     88
0.775686     88
0.306119     88
0.805875     88
0.712285     87
0.076195     87
0.972452     87
0.407821     87
1.560000     86
0.870499     86
Name: TransSup, dtype: int64
---- LN_INC ---
6.232448    45
6.413459    41
6.410175    39
6.411818    36
6.436150    35
            ..
5.680173     1
7.256297     1
6.196444     1
6.709304     1
7.461066     1
Name: LN_INC, Length: 965, dtype: int64
---- Worker ---
1    3335
0    1227
Name: Worker, dtype: int64
---- VKMS ---
37375.641970    1
3904.222324     1
11338.753720    1
16007.789850    1
7228.867298     1
               ..
6346.277652     1
18823.968310    1
20482.456540    1
10871.437080    1
14566.050410    1
Name: VKMS, Length: 4562, dtype: int64
---- LN_VKMS ---
8.016047     1
9.267165     1
8.533939     1
8.926711     1
8.071971     1
            ..
10.236381    1
10.463203    1
8.544508     1
8.873418     1
10.049679    1
Name: LN_VKMS, Length: 4562, dtype: int64

**Discuss the result** from descriptive statistics and correlation matrix

1. *Children*: Mean =0.77, Max = 5.
2. *Car*: Mean = 1.246
3. *Elderly*: Mean = 0.14
4. *HHIncome*: Mean = 620.68 and Max = 10558

### B. Estimate the linear regression using socio-economic variables

In [26]:
model = ols("VKMS ~ Car + C(Elderly) + C(Worker) + Children + HHIncome", df).fit()

In [27]:
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   VKMS   R-squared:                       0.212
Model:                            OLS   Adj. R-squared:                  0.211
Method:                 Least Squares   F-statistic:                     245.2
Date:                Mon, 13 Sep 2021   Prob (F-statistic):          1.38e-232
Time:                        14:05:49   Log-Likelihood:                -48901.
No. Observations:                4562   AIC:                         9.781e+04
Df Residuals:                    4556   BIC:                         9.785e+04
Df Model:                           5
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept        2702.9023    645.789      4.185      0.000    1436.843    3968.961
C(Elderly)[T.1]  -417.3209    630.040     -0.662      0.508   -1652.505     817.863
C(Worker)[T.1]   3414.0371    520.436      6.560      0.000    2393.731    4434.343
Car              5386.3208    387.359     13.905      0.000    4626.910    6145.732
Children         2335.2316    169.851     13.749      0.000    2002.241    2668.222
HHIncome            6.5105      0.519     12.540      0.000       5.493       7.528
==============================================================================
Omnibus:                      204.442   Durbin-Watson:                   1.060
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              223.018
Skew:                           0.524   Prob(JB):                     3.73e-49
Kurtosis:                       2.729   Cond. No.                     3.85e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.85e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

**Discuss the result**:

All of the variables have the significant effect except for Elderly variable that is no statistical evidence in average vehical km based on the elderly person in household
1. Increasment in 1 car leads to on average 5386 Vehicle km annually 
2. The average vehical km for working adult in the household is estimated to be 3414 + 2702 = 6116 km whereas only  2702 km if no working adult in household
3. An increase in 1 children leads to on average 2335 vehical km annually 
4. Similarly, increase in 1 unit of household income will increase 6 km increase.

### C. Estimate the linear regression using socio-economic variables and supply & city varibables

In [38]:
mod= ols(formula = 'VKMS ~ Car + C(Elderly) + C(Worker) + Children + HHIncome + RoadDens + TransSup + CityShape + RoadDens + TransSup + CityShape',data = df)
res = mod.fit()

In [39]:
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                   VKMS   R-squared:                       0.579
Model:                            OLS   Adj. R-squared:                  0.578
Method:                 Least Squares   F-statistic:                     782.3
Date:                Mon, 13 Sep 2021   Prob (F-statistic):               0.00
Time:                        14:25:44   Log-Likelihood:                -47472.
No. Observations:                4562   AIC:                         9.496e+04
Df Residuals:                    4553   BIC:                         9.502e+04
Df Model:                           8
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept       -7142.1580    965.003     -7.401      0.000   -9034.033   -5250.284
C(Elderly)[T.1]   -57.0727    460.853     -0.124      0.901    -960.568     846.423
C(Worker)[T.1]   3274.5519    380.606      8.604      0.000    2528.379    4020.725
Car              5353.6099    283.399     18.891      0.000    4798.011    5909.209
Children         2234.2215    124.300     17.974      0.000    1990.534    2477.910
HHIncome            6.7285      0.380     17.720      0.000       5.984       7.473
RoadDens         2.403e+04    426.956     56.288      0.000    2.32e+04    2.49e+04
TransSup        -5608.7154    264.775    -21.183      0.000   -6127.802   -5089.629
CityShape       -3016.7246    886.829     -3.402      0.001   -4755.340   -1278.109
==============================================================================
Omnibus:                      140.760   Durbin-Watson:                   1.960
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              276.593
Skew:                           0.218   Prob(JB):                     8.68e-61
Kurtosis:                       4.125   Cond. No.                     7.48e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.48e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

**Discuss the result**:

Similar to Model B, All of the variables have the significant effect except for Elderly variable that is no statistical evidence in average vehical km based on the elderly person in household
1. Increasment in 1 car leads to on average 5353 Vehicle km annually 
2. The average vehical km for working adult in the household is estimated to be 3274 - 7142 = -3868 km whereas only  -7142 km if no working adult in household
3. An increase in 1 children leads to on average 2335 vehical km annually 
4. Similarly, increase in 1 unit of household income will increase 6.7 km increase. 
5. RoadDens: Increase in 1 unit Road Density will cause average 24000 vehical km 
6. TransSup: Incrase in 1 unit Supply of mass transit will decrease -5608 vehical km 
7. CityShape: Increase in 1 unit of City shape (more in cirular shape) will reduce 3016 vehical km

### D. Compare the model from B and C.

Elderly variable is not significant in both model;however, since adjusted R-square is higher in model C (0.578 > 0.211), Model C is preferable.

### E. Calculate elasticity of VKMS with respect to household income and mass transit supply